### ISSUE TITLE
lsb_release on jessie

### ISSUE THREAD

**Issue by joerx** [docker-library/buildpack-deps#22]
Command `lsb_release` not found. This is required for some installations, e.g. MongoDB via their [official guides](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/). What would be the output of `lsb_release -sc`?

**Comment by joerx** [comment]
Ok, it's simply "jessie". Would still be nice to have the `lsb_release` command.

**Comment by tianon** [comment]
Nice to have, sure, but are they any instances of `gem install ...`, `pip install ...`, `npm install ...`, `cpanm ...` that actually fail due to this missing, especially with [`/etc/os-release`](http://www.freedesktop.org/software/systemd/man/os-release.html) cannibalizing `lsb-release` as a standard for operating system information?

**Comment by joerx** [comment]
Not really for the default packages so far, but e.g. installation instructions such as for MongoDB would fail: http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/.

**Comment by tianon** [comment]
Installing software like MongoDB isn't really the intention of
buildpack-deps, though -- from the description, buildpack-deps "includes a
large number of 'development header' packages needed by various things like
Ruby Gems, PyPI modules, etc. For example, buildpack-deps would let you do
a bundle install in an arbitrary application directory without knowing
beforehand that ssl.h is required to build a dependent module."
