### ISSUE TITLE
Audio/ogg mime type cannot be recognized 

### ISSUE THREAD

**Issue by idobrodushniy** [docker-library/buildpack-deps#76]
I have the file with mime type audio/ogg, then I put this file into docker-container with python3:latest, where is using buildpack-deps:jessie and in debian file system file has mime type application/octet-stream. Seems, that system just can't recognize the mime type and sets default type( application/octet-stream). I have tried to update the mime types lib, but it didn't give any results. Really need your help.

**Comment by dave5000** [comment]
oit ys net microsof callerie debege is sosf awer extantion visual studio rpc

**Comment by yosifkit** [comment]
`file` is showing the correct `audio/ogg` mime type. So perhaps it is something in your python application or libraries?

```console
$ docker run -it buildpack-deps:jessie

$ find / | grep ogg
/usr/share/mime/audio/ogg.xml

$ wget https://upload.wikimedia.org/wikipedia/commons/c/c8/ample.ogg

$ file --mime-type Example.ogg
Example.ogg: audio/ogg
```

Since this is not an issue with the `buildpack-deps` image, in the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
