### ISSUE TITLE
images with sudo

### ISSUE THREAD

**Issue by paleozogt** [docker-library/buildpack-deps#84]
Could we get a `-sudo` variant?

The base Ubuntu images [don't come with sudo](https://github.com/tianon/docker-brew-ubuntu-core/issues/48).  While this isn't really a problem when writing a Dockerfile, it can be a problem when using images on some CI/CD services that follow the best-practice of [not running container processes as root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

This seems to vary by CI/CD service.  Some (like GitLab) run the CI script as root in the container, while Azure Pipelines [don't](https://developercommunity.visualstudio.com/content/problem/336504/docker-container-root-user.html).

**Comment by tianon** [comment]
Even if we were to add `sudo` to these images, we would definitely not setup `NOPASSWD:` (or `sudo` group membership, for that matter), so there would still be enough setup for users of this image to do in order to be able to _use_ `sudo` that I don't think it's worth us adding.

The steps required to install it are trivial (`apt-get update && apt-get install -y sudo`), and if one combines that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with `sudo` pre-installed.
